name: clang-format Check
on:
  pull_request:
    branches: [ main ]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clang-format lint
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: '.'
          exclude: './thirdparty'
          extensions: 'h,cpp,c'
          clangFormatVersion: 13