name: clang-format Check
on:
  pull_request:
    branches: [ main ]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clang Format Github Action
        uses: RafikFarhad/clang-format-github-action@v2.0.0
        with:
          source: './sc-kpm,./sc-memory,./sc-network,./sc-server,./tools'
          style: 'file'